### PR TITLE
sync multi-tenancy  

### PR DESCRIPTION
**Pull request by RyzorBent**
Hi @j05u3 

I think the feature I'm after might after all be in the main library, in the commit https://github.com/j05u3/whatsapp-cloud-api/commit/c10439046313e30c32f5d11ed182dfa8f403a9f3

I think if this is synched over, it might provide the feature I'm after.

Regards.

### CODE REVIEW

**Comment by j05u3** [comment]
oh, I can see it allows to choose which bot you want to listen to, as a note, this will work only for whatsapp phone numbers inside the same facebook app

and also this library j05u3/whatsapp-cloud-api already supports that automatically, I mean, in your webhook you will receive messages that come to any of the whatsapp phone numbers linked to your facebook app, you can just check the `to_phone_number` parameter in the message so you can identify which was the whatsapp phone number that was meant to receive the message ✌️

**Comment by RyzorBent** [comment]
Oh, i was not aware that it is limited to just the phone numbers in the same app, as i'm planning to let companies connect using their own [phoneNumberId + tokens]. We were testing this yesterday with two profiles from two different apps, the issue was that the library is sending the message **TWICE** all the time to both numbers, so i thought https://github.com/j05u3/whatsapp-cloud-api/commit/c10439046313e30c32f5d11ed182dfa8f403a9f3 could be the answer to this problem.

So you think it won't work?

**Comment by j05u3** [comment]
> the issue was that the library is sending the message TWICE all the time to both numbers

I would want to see the code, that's weird, you mean the handler was receiving an incoming message twice? or when you used "sendMessage" it was sending it twice?

>So you think it won't work?

I think this is probably unnecessary 🤔, you can try though, you can merge it locally and use that merged version, a guide that could help is: https://urre.me/writings/test-local-npm-packages/

**Comment by RyzorBent** [comment]
I send a message once, and it get received by node js, but then `bot.on('message' ... ` indicates receives TWO messages when i debug. [the app is set up in a way to send a message when an invalid message is received, so i send one message, but both bots receives an error message] ... that i why i think the pub subscribe update might be a solution. [perhaps i'm doing something wrong here :)]

i have a this configs file which has the two bot's configs

```const botConfigs = [
  {
    phoneNumberId: process.env.BOT_ONE_WHATSAPP_PHONE_NUMBER_ID,
    token: process.env.BOT_ONE_WHATSAPP_ACCESS_TOKEN,
    webhookVerifyToken: process.env.BOT_ONE_WHATSAPP_VERIFY_TOKEN,
    webhookPath: '/webhook/yuribot',
    organizationId: 'ZPf3KF',
  },
  {
    phoneNumberId: process.env.BOT_TWO_WHATSAPP_PHONE_NUMBER_ID,
    token: process.env.BOT_TWO_WHATSAPP_ACCESS_TOKEN,
    webhookVerifyToken: process.env.BOT_TWO_WHATSAPP_VERIFY_TOKEN,
    webhookPath: '/webhook/surveyrbot',
    organizationId: 'UwtbDE',
  },
]
module.exports = botConfigs
```

the BotManager class is used to manage them 
```class BotManager {
  constructor(botConfigs, azureRedis, mongooseConnection) {
    this.azureRedis = azureRedis;
    this.mongooseConnection = mongooseConnection;
    this.bots = botConfigs.map((config) => this.initializeBot(config));
  }

  initializeBot(config) {
    const { phoneNumberId, token, webhookVerifyToken, webhookPath } = config;
    const bot = createBot(phoneNumberId, token, {
      version: 'v18.0',
      responseLogger: async (obj) => {},
    });

    bot.on('message', async (msg) => {
      const isPossibleChatWootConversation = await possibleChatWootConversation(
        msg,
        this.azureRedis
      );
      if (isPossibleChatWootConversation) {
        const isChatWootConversation = await sendMessageToChatWoot(msg, bot);
        if (isChatWootConversation) return;
      }

      await handleMessage(msg, bot, this.azureRedis, this.mongooseConnection);
    });

    bot.onStatusChange(async (status) => {
      await handleBroadcast(status, bot);
    });

    return {
      config,
      bot,
      initializeWebhook: (app) => {
        bot
          .startExpressServer({
            app,
            webhookPath: webhookPath,
            webhookVerifyToken: webhookVerifyToken,
          })
          .then(() => {
            logger.info(`Bot with phone number ID ${phoneNumberId} is initialized.`);
          })
          .catch((error) => {
            logger.error(`Error initializing bot webhook for ${phoneNumberId}: ${error}`);
          });
      },
    };
  }

  startAll(app) {
    this.bots.forEach(({ initializeWebhook }) => initializeWebhook(app));
  }

  findBotByWebhookPath(path) {
    const botInfo = this.bots.find((bot) => bot.config.webhookPath === path);
    return botInfo ? botInfo.bot : null;
  }

  getBotByOrganizationId(organizationId) {
    const botInfo = this.bots.find((bot) => bot.config.organizationId === organizationId);
    if (!botInfo) {
      logger.error(`Bot for organizationId ${organizationId} not found.`);
      return null;
    }
    return botInfo.bot;
  }
}
```
and the class is instantiated in the entry server.js 
```
const botManager = new BotManager(botConfigs, azureRedis, mongooseConnection);
botManager.startAll(app);
```

**Comment by RyzorBent** [comment]
In light of your email, i have now started the process of testing out --> https://github.com/j05u3/whatsapp-cloud-api-express

**Comment by j05u3** [comment]
just took a look at your code, I think you were right from the beginning

I believe the only extra thing that you need to do is to either:

* search for a way to receive only messages for that bot in the `.on('message'` (which can be achieved by  https://github.com/j05u3/whatsapp-cloud-api/commit/c10439046313e30c32f5d11ed182dfa8f403a9f3) 

or 

* inside the  `.on('message'` handler only process messages that are destined for that bot by looking at the `to_phone_number` attribute in the message

**Comment by j05u3** [comment]
> In light of your email, i have now started the process of testing out --> https://github.com/j05u3/whatsapp-cloud-api-express

or you can try the new library which from my point of view simplifies things ✌️

**Comment by RyzorBent** [comment]
We have successfully tested the new library, Works like a charm, We now have multi-tenancy support. Which is very big. Thank you very much @j05u3 for always being willing to help out. It really means a lot. 🙏🏾

**Comment by j05u3** [comment]
> We have successfully tested the new library, Works like a charm, We now have multi-tenancy support. Which is very big. Thank you very much @j05u3 for always being willing to help out. It really means a lot. 🙏🏾

that'great  🙌 , happy to help at least a little

**Pull request closed without merging**
